image: lapaev/image

stages:
  - build
  - test

default:
  cache:
    paths:
      - proj/DBCW/64/bin


build:
  stage: build
  
  services:
    - postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 4Nikarulez_7

        ports:
          - 5432:5432

        # set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  
  script:
    - cd proj/DBCW
    - cmake -B build -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake -Wno-dev
    - pushd build && make && popd
    - 64/bin/DA_ut
    - 64/bin/DBCW_ut
    - 64/bin/DA_int
    - 64/bin/DBCW_int
