image: lapaev/image

stages:
  - build
  - test
  
variables:
    POSTGRES_DB: "test"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "4Nikarulez_7"

default:
  cache:
    paths:
      - proj/DBCW/64/bin


build:
  stage: build
  
  services:
    - name: postgres:latest:
        
  
  script:
    - cd proj/DBCW
    - cmake -B build -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake -Wno-dev
    - pushd build && make && popd
    - 64/bin/DA_ut
    - 64/bin/DBCW_ut
    - 64/bin/DA_int
    - 64/bin/DBCW_int
