image: lapaev/image

stages:
  -build
  -test

build:
  stage: build
  script: 
    - cd 3cbdcw/proj/DBCW
    - cmake -B build
    - cd build && make

test:
  stage: test
  needs: build

  script:
    - cd 3cbdcw/proj/DBCW/64/bin/Release
    - ./DA_ut
