image: lapaev/image

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd proj/DBCW
    - cmake -B build -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake
    - pushd build && make && popd
    - ls
    - cd 64/bin && ls
    
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

test:
  stage: test
  needs: 
    - build

  script:
    - ls
    - cd proj/DBCW
    - ls
    - cd 64/bin
    - ./DA_ut
