image: lapaev/image

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd proj/DBCW
    - cmake -B build -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake
    - push build && make && popd
    
  cache:
    - key:
      files:
        - DA_ut
      paths:
        - 64/bin

test:
  stage: test
  needs: 
    - build

  script:
    - cd ENVIRONMENT
    - ./DA_ut
