image: lapaev/image

stages:
  - build
  - test

default:
  cache:
    paths:
      - proj/DBCW/64/bin


build:
  stage: build
  script:
    - cd proj/DBCW
    - cmake -B build -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake -Wno-dev
    - pushd build && make && popd
    - scripts/run_units.sh
