image: lapaev/image

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd proj/DBCW
    - cmake -B build -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake
    - cd build && make

test:
  stage: test
  needs: 
    - build

  script:
    - ls
    - proj/DBCW/64/bin/Release
    - ./DA_ut
