variables:
  Solution: DBCW.sln

before_script:
  - "echo off"
  - 'call "%vsappiddir%..\..\VC\Auxiliary\Build\vcvars64.bat" x64'
  # output environment variables (usefull for debugging, propably not what you want to do if your ci server is public)
  - echo.
  - set
  - echo.

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
  - echo building...
  - 'msbuild.exe -p:Configuration=Debug "%Solution%"'
  except:
  - tags

test:
  stage: test
  script:
  - echo testing...
  except:
  - tags

deploy:
  stage: deploy
  script:
  - echo deploying...
  only:
  - production