name: ci build

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    container: lapaev/image

    # service containers to run with `postgres-job`
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 4Nikarulez_7

        ports:
          - 5432:5432

        # set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        pwd
        ls -a
        cd proj/DBCW
        cmake -B build -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake -Wno-dev
        cd build && make -j 8
    - name: Unit tests
      run: |
        cd proj/DBCW/64/bin
        chmod +x DA_ut
        ./DA_ut
        chmod +x DBCW_ut
        ./DBCW_ut
    - uses: actions/upload-artifact@master
      with:
        name: build-artifact
        path: ./build
    - name: install psql
      run: apt install -y postgresql postgresql-contrib
    - name: test psql
      run: psql -h postgres "sslmode=disable user=postgres port=5432 password=4Nikarulez_7"
    - name: migrate_database
      run: |
        cd proj/sql/test
        psql -h postgres "sslmode=disable user=postgres port=5432 password=4Nikarulez_7" <test.sql
    - name: Integration tests
      run: |
        cd proj/DBCW/64/bin
        ls -a
        chmod +x DA_int
        ./DA_int
        chmod +x DBCW_int
        ./DBCW_int
    - uses: actions/upload-artifact@master
      with:
        name: build-artifact
        path: ./build
    - name: E2E tests
      run: |
        cd proj/DBCW/64/bin
        ls -a
        chmod +x Main
        ./Main 8000 & ../../TESTS/python3 e2e.py
    - uses: actions/upload-artifact@master
      with:
        name: build-artifact
        path: ./build


